### ISSUE TITLE
Question about architecture `open`

### ISSUE THREAD

**Issue by ArtemIsmagilov** [YoSTEALTH/Shakti#2]
this is a wonderful job. why did you decide to work with the descriptor through functions rather than through methods like the standard `open`?

**Comment by ArtemIsmagilov** [comment]
Do I understand correctly that this way we can work with any file descriptor? this is very cool!

**Comment by YoSTEALTH** [comment]
[open()](https://github.com/YoSTEALTH/Shakti/blob/master/src/shakti/io/file.pyx#L1) works more like how [os.open()](https://docs.python.org/3/library/os.html#os.open) does in python `os` module. Currently it returns file descriptor, later you can choose to return direct descriptor as well (this will require enabling registering and so on...)

I do have plans to create `File` class, this will be close to how `open` works in python. e.g:
```python
async with File('./path', 'r') as file:
    await file.read()
```

Currently its summer time here so I am busy with other things, as I get time I slowly add new features to this project.

**Comment by ArtemIsmagilov** [comment]
Thanks for answering
